### ISSUE TITLE
Issue using jquery to add stackbox

### ISSUE THREAD

**Issue by Hannibaal003** [stebru/stackbox#7]
When I try to call an element using jquery to add stackbox to it, I get an error in jquery.stackbox.js on line 615 

isHttp = (content.match(/^https?:\/\//) || content.charAt(0) === '/');

Uncaught TypeError: undefined is not a functionjquery.stackbox.js:615 v.addContentjquery.stackbox.js:285 v.initjquery.stackbox.js:1225 (anonymous function)jquery.min.js:2 m.extend.eachjquery.min.js:2 m.fn.m.eachjquery.stackbox.js:1179 a.fn.stackboxdeal.js:46 (anonymous function)jquery.min.js:2 m.Callbacks.jjquery.min.js:2 m.Callbacks.k.fireWithjquery.min.js:2 m.extend.readyjquery.min.js:2 J

![stackbox_err](https://cloud.githubusercontent.com/assets/11465275/6802281/11b54c32-d1fd-11e4-8bac-a10ba3ae3619.JPG)

using the HTML5 extensions work, but I really need the jquery calls to work.

Regards,
Dexter

**Comment by draganhfc** [comment]
I have the same issue so this should be fixed.

**Comment by stebru** [comment]
Thanks for filing this!

I think only my lousy documentation is to blame, though, so I have provided a (hopefully) clearer demo of using Stackbox with a jQuery selector over on CodePen: http://codepen.io/stebru/pen/oXZErp

Please let me know if this is still a problem, and I will re-open this issue and look into it more.

**Comment by stebru** [comment]
I have also updated the docs: http://stefan.codes/stackbox/

**Comment by Hannibaal003** [comment]
Great News!!  I will give it a shot in the morning.  Thank you for
following up.

Regards,

Dexter
